package App::Followme::Initialize;
use 5.008005;
use strict;
use warnings;

use Cwd;
use IO::File;
use MIME::Base64  qw(decode_base64);
use File::Spec::Functions qw(splitdir catfile);

our $VERSION = "1.15";

require Exporter;
our @ISA = qw(Exporter);
our @EXPORT_OK = qw(initialize);

use constant CMD_PREFIX => '#>>>';

#----------------------------------------------------------------------
# Initialize a new web site

sub initialize {
    my ($directory, $choice) = @_;

    chdir($directory) if defined $directory;
    my ($read, $unread) = data_readers();

    my %var;
    my $checked = 0;
    while (my ($command, $lines) = next_command($read, $unread)) {
        my @args = split(' ', $command);
        my $cmd = shift @args;

        write_error("Missing lines after command", $command)
            if $cmd eq 'copy' && @$lines == 0;

        write_error("Unexpected lines after command", $command)
            if $cmd ne 'copy' && @$lines > 0;

        if ($cmd  eq 'copy') {
            check_choice($var{dir}, $choice) unless $checked ++;
            copy_file($choice, $lines, @args);

        } elsif ($cmd eq 'set') {
            write_error("No name in set command", $command) unless @args;
            my $name = shift(@args);
            $var{$name} = \@args;

        } else {
            write_error("Error in command name", $command);
        }
    }

    return;
}

#----------------------------------------------------------------------
# Check choice against list of directories

sub check_choice {
    my ($dirs, $choice) = @_;
    $dirs = [] unless $dirs;

    foreach my $dir (@$dirs) {
        return if $dir eq $choice;
    }

    my $msg = "Please choose one of the following options for init:\n";
    $msg .= join(' ', @$dirs) . "\n";
    die $msg;
}

#----------------------------------------------------------------------
# Create a copy of the input file

sub copy_file {
    my ($choice, $lines, $mode, $dir, $file) = @_;
    return unless $dir eq 'common' || $dir eq $choice;

    create_dirs($file);
    my $out = IO::File->new($file, 'w') or die "Couldn't write $file: $!\n";

    if ($mode eq 'binary') {
        binmode($out);
        foreach my $line (@$lines) {
            print $out decode_base64($line);
        }

    } else {
        foreach my $line (@$lines) {
            print $out $line;
        }
    }

    close($out);
    return;
}

#----------------------------------------------------------------------
# Check path and create directories as necessary

sub create_dirs {
    my ($file) = @_;

    my @dirs = splitdir($file);
    pop @dirs;

    my @path;
    while (@dirs) {
        push(@path, shift(@dirs));
        my $path = catfile(@path);

        if (! -d $path) {
            mkdir ($path) or die "Couldn't create $path: $!\n";
        }
    }

    return;
}

#----------------------------------------------------------------------
# Return closures to read the data section of this file

sub data_readers {
    my @pushback;

    my $read = sub {
        if (@pushback) {
            return pop(@pushback);
        } else {
            return <DATA>;
        }
    };

    my $unread = sub {
        my ($line) = @_;
        push(@pushback, $line);
    };

    return ($read, $unread);
}

#----------------------------------------------------------------------
# Is the line a command?

sub is_command {
    my ($line) = @_;

    my $command;
    my $prefix = CMD_PREFIX;

    if ($line =~ s/^$prefix//) {
        $command = $line;
        chomp $command;
    }

    return $command;
}

#----------------------------------------------------------------------
# Get the name and contents of the next file

sub next_command {
    my ($read, $unread) = @_;

    my $line = $read->();
    return unless defined $line;

    my $command = is_command($line);
    die "Command not supported: $line" unless $command;

    my @lines;
    while ($line = $read->()) {
        if (is_command($line)) {
            $unread->($line);
            last;

        } else {
            push(@lines, $line);
        }
    }

    return ($command, \@lines);
}

#----------------------------------------------------------------------
# Die with error

sub write_error {
    my ($msg, $line) = @_;
    die "$msg: " . substr($line, 0, 30) . "\n";
}

1;
__DATA__
#>>> set dir one-fixed two-full three-full one-full
#>>> copy text common LICENCE
Copyright (c) 2015 Russ Weakley, Max Design

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated  files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#>>> copy binary common apple-touch-icon.png
iVBORw0KGgoAAAANSUhEUgAAADkAAAA5CAMAAAC7xnO3AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJ
bWFnZVJlYWR5ccllPAAAAyJpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdp
bj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6
eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEz
NDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJo
dHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlw
dGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAv
IiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RS
ZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpD
cmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNSBNYWNpbnRvc2giIHhtcE1NOkluc3RhbmNl
SUQ9InhtcC5paWQ6OTQyNDQ4QzFCN0JGMTFFNDkxQkJDN0Y1NDU1M0I5NzQiIHhtcE1NOkRvY3Vt
ZW50SUQ9InhtcC5kaWQ6OTQyNDQ4QzJCN0JGMTFFNDkxQkJDN0Y1NDU1M0I5NzQiPiA8eG1wTU06
RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo5NDI0NDhCRkI3QkYxMUU0OTFC
QkM3RjU0NTUzQjk3NCIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDo5NDI0NDhDMEI3QkYxMUU0
OTFCQkM3RjU0NTUzQjk3NCIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1w
bWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pr6m70MAAAAqUExURYKDhBUXF9DR0WNkZaGiou/w8CQm
JzQ2NuDg4JKTk7GyssHBwQUHCP///4yJslkAAAErSURBVHja3NfbDsMgCABQvNZ6+f/fXbYmnaCg
G2/ltT2JFgUK7d+AR8hU4IqSfpHZxfqN6PKeDGAqDQNhLSfusgtpY+UiWkmeVYqTl67K4Ti5gpjC
LxBR2NzjuNdb2roXdpBxU0YqQXgZHw7AMhge+mb7pyYgCRJsmAKSRoSYml7mBcQ0d9KtIKKukyQl
Rzoo7Gn8ykRgaOGgsDV/v5BuWShsH4pht9xySxjgm7LwyssgjzCtdGNGqdyBU7kFr7QQee7A+Wr9
BmS+kF/DTpYq0BF2+UyVpxPYnSFybv0CRv6ueBGiu5I3buX8fg41wQvQyHXIs5DUobH2eQ6S2jcp
fkwLpvVWUeMVfeX/Xqbon4qerZgTFLOJYh5SzGCauU8xa6rm2wf+AbwEGAAVbZbbwk3XrgAAAABJ
RU5ErkJggg==
#>>> copy binary common favicon.ico
AAABAAQAEBAAAAEAIAAoBQAARgAAACAgAAABACAAKBQAAG4FAAAwMAAAAQAgACgtAACWGQAAAAAA
AAEAIACLGAAAvkYAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAgAAAAAAAAAATExMRjc3N6kqKirkFxcX/xcXF/8qKirkNzc3qUxMTEYAAAAAAAAAAAAAAAIA
AAAAAAAAAgAAAACIiIgPPj4+pxsbG/8AAAD/AAAA/wYGBv4AAAD+AAAA/wAAAP8bGxv/Pj4+p4iI
iA8AAAAAAAAAAgAAAACIiIgPPT09zgAAAP8AAAD7CgoK+gYGBv0AAAD+FBQU/gAAAP0BAQH7AAAA
+wAAAP89PT3OiIiIDwAAAAAAAAAAPj4+pwAAAP8AAAD4Dg4O/gAAAP4BAQH+RkZG/gAAAP4aGhr+
AAAA/gEBAf4AAAD3AAAA/z4+PqcAAAAATExMRhsbG/8AAAD7Dg4O/g8PD/4AAAD+wsLC/u/v7/5f
XV3+AAAA/iAgIP4AAAD+AQEB/gAAAPsbGxv/TExMRjc3N6kAAAD/DAwM+w4ODv4AAAD+vr6+/v//
//7////+7+/v/2BgYP4AAAD+ICAg/gAAAP8BAQH7AAAA/zc3N6kqKirkAAAA/wUFBf0AAAD+vr6+
/v////79/f3++/v7/v////7v7+/+YGBg/gAAAP4gICD+AAAA/QAAAP8qKirkGBgY/w8PD/4AAAD+
wcLB/v////78/Pz+/f39/v////77+/v+/////u/v7/5gYGD+AAAA/hYWFv4AAAD+FxcX/xgYGP8O
Dg7+AAAA/rS0tP7////+/////v39/f719fX+/////vv6+v7////+7e3t/mhoaf4AAAD+DAwM/hcX
F/8qKirkAAAA/w4ODv0AAAD+rKys/v////6xsbH+XFxc/u/v7/7////++fn5/v////7e3t7+AAAA
/QYGBv8sLCzkNzc3qQAAAP8FBQX7BgYG/gAAAP56enr+CQkJ/gAAAP5hYWH+7e3t/v////7t7e3+
bGxs/gAAAPsNCwv/Nzc3qUxMTEYbGxv/AAAA+wUFBf4ODg7+AAAA/gYGBv4jIyP+AAAA/mlpaf7e
3t7+bGxs/gAAAP4RERH7Gxsb/0xMTEYAAAAAPj4+pwAAAP8AAAD3BAQE/hQUFP4DAwP+AAAA/hYW
Fv4AAAD+AAAA/gAAAP4UFBT3AAAA/z4+PqcAAAAAAAAAAIiIiA89PT3OAAAA/wAAAPsBAQH6AQEB
/QAAAP4AAAD+Dw8P/Q4ODvsGBgb7AAAA/z09Pc6IiIgPAAAAAAAAAAIAAAAAiIiIDz4+PqcbGxv/
AAAA/wAAAP8AAAD+AAAA/gAAAP8AAAD/Gxsb/z4+PqeIiIgPAAAAAAAAAAIAAAAAAAAAAgAAAAAA
AAAATExMRjc3N6kqKirkFxcX/xcXF/8qKirkNzc3qUxMTEYAAAAAAAAAAAAAAAIAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABQAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAAAAAAAf39/MF1dXXs9PT2y
QUFB5S0tLf8AAAD+AAAA/i0tLf9BQUHlPT09sl1dXXt/f38wAAAAAAAAAAAAAAACAAAAAgAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAaWlpRkVF
RbcvLy/6Gxsb/wAAAP8AAAD/AAAA/wICAv8CAgL/AAAA/gAAAP8AAAD/Gxsb/y8vL/pFRUW3aWlp
RgAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAA
l5eXG1VVVawuLi7/AAAA/wAAAP8AAAD6AQEB/AUFBf4CAgL/AQEB/wAAAP4BAQH+BQUF/gEBAfwA
AAD7AAAA/wAAAP8tLS3/VVVVrJeXlxsAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAADAAAAAHl5eT1AQEDoAAAA/wAAAPwEBAT7AQEB/gAAAP4AAAD+AQEB/wAAAP4BAQH/AAAA
/gAAAP4BAQH/AAAA/gEBAf8BAQH+BAQE+wAAAPwAAAD/QEBA6Hl5eT0AAAAAAAAAAwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAABAAAAACLi4tWPDw8/wAAAP8FBQX7AQEB/gAAAP4BAQH/AQEB/wEBAf8B
AQH/AQEB/wEBAf8BAQH/AAAA/gEBAf8BAQH/AQEB/wEBAf8BAQH/AwMD/wUFBfsAAAD/PDw8/4uL
i1YAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAMAAAAAeXl5PTw8PP8AAAD/CQkJ/AEBAf8BAQH/AQEB
/wEBAf8BAQH/AAAA/wYGBv8bGxv/BQUF/wAAAP8BAQH/AQEB/wEBAf8BAQH/AQEB/wEBAf8BAQH/
AQEB/wYGBvwAAAD/PDw8/3l5eT0AAAAAAAAAAwAAAAAAAAACAAAAAJeXlxtAQEDoAAAA/wkJCfwA
AAD/AQEB/wEBAf8AAAD+AQEB/wAAAP8LCwv/CgoK/wAAAP8PDw//CgoK/wAAAP4BAQH/AQEB/wEB
Af8BAQH/AQEB/wEBAf8BAQH/AAAA/wYGBvwAAAD/QEBA6JeXlxsAAAAAAAAAAgAAAAIAAAAAVVVV
rAAAAP8FBQX6AQEB/wAAAP4BAQH/AQEB/wAAAP4AAAD/Dg4O/gAAAP8GBgb/j4+P/wAAAP8AAAD/
CQkJ/gAAAP8AAAD+AQEB/wEBAf8BAQH/AQEB/wAAAP4AAAD+AQEB/wUFBfoAAAD/VVVVrAAAAAAA
AAACAAAAAGlpaUYtLS3/AAAA/AEBAf4BAQH/AQEB/wAAAP4AAAD+AAAA/hAQEP8ODg7+AAAA/sHB
wf//////t7e3/gAAAP4UFBT+CwsL/wAAAP4AAAD+AQEB/wEBAf8AAAD+AAAA/gAAAP4BAQH/AQEB
/gAAAPwuLi7/aWlpRgAAAAAAAAAARUVFtwAAAP8EBAT8AQEB/wEBAf8BAQH/AQEB/wAAAP4ODg7+
EBAQ/wAAAP/BwsH///////7+/v//////uLi4/gAAAP4YGBj/CwsL/wAAAP8BAQH/AQEB/wEBAf8A
AAD+AAAA/gEBAf8AAAD+BAQE/AAAAP9FRUW3AAAAAH9/fzAvLy/6AAAA/wEBAf4AAAD+AQEB/wEB
Af8AAAD/Dg4O/g4ODv4AAAD/wcHB/v/////9/v3//f79//7+/v/////+uLi4/gAAAP8WFhb+CwsL
/wAAAP8BAQH/AQEB/wAAAP4AAAD+AQEB/wAAAP4BAQH+AAAA/i8vL/p/f38wXV1dexsbG/8AAAD7
AAAA/gEBAf8BAQH/AAAA/hAQEP8ODg7+AAAA/sHBwf/////+/f39//7+/v/////+/v7+//////7/
///+uLi4/wAAAP4YGBj/CwsL/wAAAP4BAQH/AAAA/gAAAP4BAQH/AAAA/gAAAP4AAAD7Gxsb/11d
XXs9PT2yAAAA/wEBAfwBAQH/AQEB/wAAAP8QEBD/EhIS/wAAAP/CwsL+//////39/f/+/v7/////
//7//v///////v7+//////7/////uLi4/wAAAP8YGBj/CwsL/wAAAP8BAQH/AAAA/gEBAf8BAQH/
AQEB/wEBAfwAAAD/PT09skFBQeUAAAD/BQUF/gEBAf8AAAD/DQ0N/w0NDf8AAAD/wsLC///////+
/v7//v7+//7//v/////////////////+/v7//v7+//7+/v//////uLi4/wAAAP8YGBj/CwsL/wAA
AP8BAQH/AQEB/wEBAf8BAQH/BQUF/gAAAP9BQUHlLS0t/wAAAP4CAgL/AQEB/wYGBv8GBgb/AAAA
/8HBwf///////f39/v7+/v/+/v7//v/+///////+//7///////7+/v/////+/v7+//7+/v//////
uLi4/wAAAP8YGBj/CwsL/wAAAP4BAQH/AQEB/wEBAf8CAgL/AAAA/y0tLf8AAAD+AAAA/gEBAf8B
AQH+FxcX/wAAAP/BwcH///////z8/P/////+/v7+//////7//////v7+//39/f///////v7+////
//7+/v7//////v7+/v//////uLi4/wAAAP8XFxf/CQkJ/gAAAP8AAAD+AQEB/wEBAf8CAgL/AAAA
/gAAAP4AAAD+AQEB/wAAAP4PDw/+AAAA/6SkpP/////+/////v39/f7+/v7//////v////7+/v7/
//////////7////+/////v7+/v/////+/////v7+/v//////uLi4/gAAAP4TExP+CgoK/wAAAP4A
AAD+AQEB/wICAv8AAAD+LS0t/wAAAP4CAgL/AAAA/gEBAf8XFxf/AAAA/5qamv/////+/////v7+
/f/+/v7///////7+/v/Z2dn///////////79/f3+/v/+//7+/v/+/v7//v7+//7+/v//////uLi4
/gAAAP4GBgb/BgYG/wEBAf8CAgL/AAAA/y0tLf9BQUHlAAAA/wQEBP4AAAD+AQEB/wAAAP8iIiL/
AAAA/5qamv7////+/v////39/f7/////sLCw/wAAAP+5urn//////v39/f7+/v7//////v7+/v/+
//7//v7+//7+/v/////+vr6+/gAAAP8PDw/+AwMD/wUFBf4AAAD/QUFB5T09PbIAAAD/AQEB/AAA
AP4BAQH/AQEB/wAAAP4kJCT/AAAA/pmZmf7//////////q6urv8AAAD/HR0d/gAAAP+4uLj+////
/v7+/v////3+/v7+//7+/v/////+/f39//////7Dw8P+AAAA/w8PD/4BAQH+AQEB/AAAAP89PT2y
XV1dexsbG/8AAAD7AQEB/wEBAf8BAQH/AQEB/wEBAf8iIiL/AAAA/qOjo/+ysrL/AAAA/xsbG/8Q
EBD/GBcY/wAAAP+4uLj+//////7+/v/+/v7//v7+//3+/f//////vb29/wAAAP4CAgL/BwcH/wEB
Af8AAAD7Gxsb/11dXXt/f38wLy8v+gAAAP8BAQH+AQEB/wEBAf8BAQH/AQEB/wAAAP8YGBj/AAAA
/wAAAP8UFBT/BQUF/wAAAP8NDQ3/GBgY/wAAAP+4uLj///////7+/v/9/f3//////76+vv8AAAD/
EhIS/w0NDf8AAAD/AwMD/wAAAP8vLy/6f39/MAAAAABFRUW3AAAA/wQEBPsBAQH/AQEB/wEBAf8B
AQH/AQEB/wAAAP4VFRX/GBgY/wICAv8BAQH/AQEB/wAAAP8LCwv/FBQU/gAAAP+4uLj/////////
//++vr7/AAAA/xQUFP8MDAz+AAAA/wEBAf8EBAT8AAAA/0VFRbcAAAAAAAAAAGlpaUYtLS3/AAAA
/AMDA/8BAQH/AAAA/gEBAf8BAQH/AAAA/gICAv8AAAD+AQEB/wEBAf8BAQH/AQEB/wAAAP8JCQn+
FxcX/wAAAP6+vr7/w8PD/wAAAP8SEBL/Dw8P/wAAAP4BAQH/AQEB/gAAAPwuLS7/aWlpRgAAAAAA
AAACAAAAAFVVVawAAAD/BQUF+wEBAf8BAQH/AAAA/gAAAP4AAAD+AQEB/wAAAP4AAAD+AQEB/wEB
Af8AAAD+AAAA/gAAAP4KCgr/BAQE/gAAAP4AAAD/AgIC/woKCv4AAAD+AAAA/gEBAf8FBQX6AAAA
/1VVVawAAAAAAAAAAgAAAAIAAAAAl5eXG0BAQOcAAAD/BgYG/AAAAP8BAQH/AAAA/gAAAP4BAQH/
AQEB/wEBAf8BAQH/AQEB/wEBAf8AAAD+AAAA/gAAAP8GBgb/EhIS/xISEv8HBwf/AAAA/wAAAP4A
AAD/BgYG/AAAAP9AQEDnl5eXGwAAAAAAAAACAAAAAAAAAAMAAAAAeXl5PT48Pv8AAAD/BgYG/AEB
Af8AAAD+AAAA/gEBAf8AAAD+AQEB/wEBAf8BAQH/AQEB/wAAAP4AAAD+AQEB/wAAAP4DAwP/AwMD
/wAAAP8BAQH/AAAA/wYGBvsAAAD/PDw8/3l5eT0AAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAQAAAAA
i4uLVjw8PP8AAAD/BQUF+gEBAf4AAAD+AQEB/wAAAP4BAQH/AQEB/wAAAP4BAQH/AAAA/gAAAP4B
AQH/AAAA/gEBAf8BAQH/AAAA/gMDA/8FBQX6AAAA/zw8PP+Li4tWAAAAAAAAAAQAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAMAAAAAeXl5PUBAQOgAAAD/AAAA/AQEBPsBAQH+AQEB/wEBAf8BAQH/AQEB
/wEBAf8BAQH/AAAA/gEBAf8AAAD+AgIC/wMDA/8EBAT8AAAA/AAAAP9AQEDoeXl5PQAAAAAAAAAD
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAl5eXG1VVVawuLi7/AAAA/wAAAP8A
AAD7AQEB/AUFBf4CAgL/AQEB/wEBAf8CAgL/BQUF/gEBAfwAAAD7AAAA/wAAAP8uLi7/VVVVrJeX
lxsAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAA
AGlpaUZFRUW3Ly8v+hsbG/8AAAD/AAAA/wAAAP8CAgL/AgIC/wAAAP4AAAD/AAAA/xsbG/8vLy/6
RUVFt2lpaUYAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAIAAAACAAAAAAAAAAB/f38wXV1dez09PbJBQUHlLS0t/wAAAP4AAAD+LS0t/0FB
QeU9PT2yXV1de39/fzAAAAAAAAAAAAAAAAIAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAw
AAAAYAAAAAEAIAAAAAAAAC0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABAAAAAAAAAAAAAAAAo6OjHHl5eVBUVFR/Pj4+
qFxcXORERET/AAAA/gAAAP4AAAD+AAAA/kRERP9cXFzkPj4+qFRUVH95eXlQo6OjHAAAAAAAAAAA
AAAAAAAAAAEAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAwAAAAAAAAAA////BHd3
d0JfX1+YSUlJ3zIyMv8ZGRn/AgIC/wAAAP8AAAD+AwMD/gICAv8CAgL/AwMD/gAAAP4AAAD/AgIC
/xkZGf80NDT/SUlJ31xcXJh3d3dC////BAAAAAAAAAAAAAAAAwAAAAIAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMA
AAAAAAAAAP///wF2dnZJT09PszU1Nf0PDw//AAAA/wAAAP8AAAD/AAAA/QYGBv4HBwf/AAAA/gEB
Af4BAQH+AAAA/gcHB/8GBgb+AAAA/QAAAP8AAAD/AAAA/xAQEP81NTX9T09Ps3Z2dkkAAAAAAAAA
AAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAPz8/BAAAAAAAAAAAj4+PJ2ZmZqc+Pj7/AAAA/wAAAP8AAAD8AQEB/AEBAfwB
AQH9AQEB/QUFBf4DAwP+AgIC/wEBAf4BAQH+AgIC/wMDA/4FBQX+AQEB/QEBAf0BAQH8AQEB/AAA
APwAAAD/AAAA/z4+Pv9mZmanj4+PJwAAAAAAAAAAPz8/BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMFAAAAAAAAAACEhIRgR0dH5QEBAf8AAAD/
AAAA+wQEBPwDAwP9BAQE/gMDA/8CAgL/AgIC/wAAAP4AAAD+AQEB/gEBAf4BAQH+AQEB/gAAAP4A
AAD+AgIC/wICAv8DAwP/BAQE/gMDA/0EBAT8AAAA+wAAAP8CAgL/SEhI5ISEhGAAAAAAAAAAADMz
MwUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAA////
AmRkZIE7Ozv/AAAA/wAAAPoGBgb8AQEB/gEBAf4CAgL/AAAA/gICAv8BAQH+AQEB/gEBAf4CAgL/
AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4CAgL/AAAA/gICAv8BAQH+AQEB/gYGBvwA
AAD6AAAA/zs7O/9kZGSB////AgAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAMzMzBQAAAAD///8IcnJyoTIyMv8AAAD/BQUF+QYGBv4CAgL/AgIC/wAAAP4BAQH+AQEB
/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+
AQEB/gEBAf4AAAD+AgIC/wICAv8GBgb+BQUF+QAAAP8yMjL/cnJyof///wgAAAAAMzMzBQAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz8EAAAAAP///wJycnKhLi4u/wAAAP8PDw/7AwMD/wAA
AP4AAAD+AQEB/gEBAf4CAgL/AQEB/gEBAf4BAQH+AQEB/gEBAf4AAAD+AAAA/gEBAf4BAQH+AQEB
/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gAAAP4AAAD+AwMD/w8PD/sAAAD/
Li4u/3JycqH///8CAAAAAD8/PwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAGRkZIEy
MjL/AAAA/wwMDPoCAgL/AAAA/gICAv8BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gAA
AP4ODg7+AwMD/gAAAP4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB
/gEBAf4CAgL/AAAA/gICAv8MDAz6AAAA/zIyMv9kZGSBAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAA
AAAAAgAAAAAAAAAAhISEYDs7O/8AAAD/Dw8P+wICAv8AAAD+AgIC/wEBAf4BAQH+AgIC/wEBAf4C
AgL/AQEB/gEBAf4BAQH+AAAA/hYWFv4GBgb+FhYW/gQEBP4AAAD+AQEB/gEBAf4BAQH+AQEB/gEB
Af4BAQH+AQEB/gEBAf4BAQH+AgIC/wEBAf4BAQH+AgIC/wAAAP4CAgL/Dw8P+wAAAP87Ozv/hISE
YAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAwAAAACPj48nR0dH5QAAAP8FBQX6AwMD/wAAAP4BAQH+
AQEB/gEBAf4CAgL/AQEB/gEBAf4CAgL/AQEB/gICAv8AAAD+HBwc/gAAAP4AAAD/AAAA/hsbG/8F
BQX+AAAA/wEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gICAv8BAQH+AQEB/gEB
Af4AAAD+AwMD/wUFBfoAAAD/SUdJ5Y+PjycAAAAAAAAAAwAAAAAAAAADAAAAAAAAAABmZmanAQEB
/wAAAPoGBgb+AAAA/gEBAf4BAQH+AQEB/gICAv8BAQH+AgIC/wEBAf4CAgL/AAAA/gAAAP8jIyP+
AAAA/isrK/61tbX/eXl5/gAAAP8YGBj+EhIS/wAAAP4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4B
AQH+AQEB/gICAv8CAgL/AQEB/gEBAf4BAQH+AAAA/gYGBv4AAAD6AgIC/2ZmZqcAAAAAAAAAAAAA
AAMAAAABAAAAAHZ2dkk+Pj7/AAAA/wYGBvwCAgL/AAAA/gICAv8BAQH+AgIC/wEBAf4CAgL/AQEB
/gEBAf4CAgL/AAAA/iYmJv8AAAD+AAAA/sTExP7/////6enp/mpqav8AAAD+IiIi/wwMDP4AAAD+
AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gICAv8CAgL/AQEB/gEBAf4BAQH+AAAA/gICAv8G
Bgb8AAAA/z4+Pv92dnZJAAAAAAAAAAEAAAAA////BE9PT7MAAAD/AAAA+wEBAf4BAQH+AQEB/gEB
Af4CAgL/AgIC/wICAv8BAQH+AQEB/gEBAf4AAAD+JCQk/gAAAP4AAAD+xcXF/v////7////+////
/ujo6P5qamr+AAAA/iAgIP4KCgr+AAAA/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+
AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AAAA+wAAAP9PT0+z////BAAAAAAAAAAAd3d3QjU1Nf0A
AAD/BAQE/QEBAf4AAAD+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gAAAP4kJCT+AAAA/gAA
AP7FxcX+/////v////78/Pz+/f39/v////7o6Oj+ampq/gAAAP4hISH+CgoK/gAAAP4BAQH+AQEB
/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gAAAP4BAQH+BAQE/QAAAP81NTX9
d3d3QgAAAAAAAAAAXFxcmA8PD/8AAAD9AwMD/QICAv8BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4B
AQH+AAAA/iQkJP4AAAD+AAAA/sXFxf7////+/////vz8/P7////+/////v39/f7////+6Ojo/mlp
af4AAAD+ISEh/goKCv4AAAD+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB
/gEBAf4CAgL/AwMD/QAAAP0PDw//XFxcmAAAAACjo6McSEhI3wAAAP8BAQH8BAQE/gAAAP4BAQH+
AQEB/gEBAf4BAQH+AQEB/gEBAf4AAAD+JCQk/gAAAP4AAAD+xcXF/v////7////+/Pz8/v////7/
///+/////v////79/f3+/////ujo6P5paWn+AAAA/iMjI/4JCQn+AAAA/gEBAf4BAQH+AQEB/gEB
Af4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4AAAD+BAQE/gEBAfwAAAD/SEhI36Ojoxx5eXlQMjIy
/wAAAP8BAQH8AwMD/wAAAP4BAQH+AQEB/gEBAf4BAQH+AAAA/gAAAP4kJCT+AAAA/gAAAP7FxcX+
/////v////78/Pz+/////v////7////+/////v////7////+/f39/v////7p6ef+aWlp/gAAAP4j
IyP+CQkJ/gAAAP4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4AAAD+AwMD/wEB
AfwAAAD/MjIy/3l5eVBUVFR/GRkZ/wAAAP8BAQH9AgIC/wEBAf4BAQH+AQEB/gEBAf4AAAD+AAAA
/iQkJP4AAAD+AAAA/sXFxf7////+/////vz8/P7////+/////v////7////+/////v////7////+
/f/9/v39/f7////+6enp/mlpaf4AAAD+IyEj/goKCv4AAAD+AQEB/gEBAf4BAQH+AQEB/gEBAf4B
AQH+AQEB/gEBAf4BAQH+AgIC/wEBAf0AAAD+GRkZ/1RUVH8+Pj6oAgIC/wAAAP0BAQH9AAAA/gEB
Af4BAQH+AQEB/gAAAP4AAAD+JCQk/gAAAP4AAAD+xcXF/v////7////+/Pz8/v////7////+////
/v////7////+/////v////7////+/////v3//f79/f3+/////unp6f5paWn+AAAA/iEhIf4KCgr+
AAAA/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AAAA/gEBAf0AAAD9AgIC/z4+Pqhc
XFzkAAAA/wYGBv4FBQX+AAAA/gEBAf4BAQH+AAAA/gAAAP4kJCT+AAAA/gAAAP7FxcX+/////v//
//78/Pz+/////v////7////+/////v////7////+/////v////7////+/////v////79//3+/f39
/v////7p6ef+aWlp/gAAAP4hISH+CgoK/gAAAP4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+
AAAA/gUFBf4GBgb+AAAA/1xcXORERET/AAAA/gcHB/8DAwP+AAAA/gEBAf4AAAD+AAAA/h4eHv8A
AAD/AAAA/8XFxf////////////z8/P7//////////v7+/v/////+/////v////7+/v7//////v7/
/v/////+/v7+//////7////+/////v39/f7////+6enn/mlpaf4AAAD+ICAg/g0NDf8AAAD+AQEB
/gEBAf4BAQH+AQEB/gEBAf4BAQH+AAAA/gMDA/4HBwf/AAAA/kRERP8AAAD+AwMD/gAAAP4BAQH+
AQEB/gEBAf4AAAD+FxcX/gAAAP4jIyP+w8PD/v////7////+/f38/v////7////+/////v////7/
///+/////v////7////+/////v////7////+/////v////7////+/////v3//f79/f3+/////ujo
6P5qamr+AAAA/iAgIP4MDAz+AAAA/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4AAAD+AwMD
/gAAAP4AAAD+AQEB/gICAv8BAQH+AQEB/gAAAP4WFhb+AAAA/gAAAP+8vLz////////////8/Pz/
//////////7+/v7//////v7//v/////+/////v////79/f3//////v7//v/////+/v7+//////7/
///+/////v////7////+/f39/v////7o6Oj+ampq/gAAAP8gICD+Dg4O/gAAAP4BAQH+AQEB/gEB
Af4BAQH+AQEB/gEBAf4BAQH+AQEB/gAAAP4AAAD+AgIC/wICAv8BAQH+AQEB/gAAAP4KCgr+BgYG
/gAAAP6YmJj+9vb2/v////79/fz+/////v////7////+/////v////7////+/////v3//f7////+
/////v////7////+/////v////7////+/////v////7////+/////v39/f7////+6Ojo/mpqav4A
AAD+ICAg/g8PD/4AAAD+AQEB/gAAAP4BAQH+AQEB/gEBAf4BAQH+AQEB/gAAAP4AAAD+AwMD/gAA
AP4BAQH+AQEB/gEBAf4AAAD+Dw8P/gcHB/8AAAD/jY2N//X19f///////Pz8//////7/////////
/v7+/v/////+/f39/v////7//////////v7+/v/////+//////////7////+/////v////7////+
/////v////79/f3+/////ujo6P9qamr+AAAA/h0dHf4ODg7+AAAA/gEBAf4AAAD+AQEB/gEBAf4A
AAD+AwMD/gAAAP5ERET/AAAA/gcHB/8DAwP+AAAA/gEBAf4BAQH+AAAA/g8PD/4AAAD+AAAA/o6O
jv719fX+/////vz8/P7////+/////v////78/Pz+/////vr6+v66urr+4+Pj/v////7////+/f39
/v////7////+/////v////7////+/////v////7////+/f39/v////7o6Oj+aWlp/gAAAP4ODg7+
CgoK/gAAAP4BAQH+AAAA/gMDA/4HBwf/AAAA/kRERP9cXFzkAAAA/wYGBv4FBQX+AAAA/gEBAf4B
AQH+AQEB/gAAAP4YGBj+Dg4O/gAAAP6Ojo7+9fX1/v////78/Pz+/////vz8/P7////+/////qqq
qv4AAAD+Z2dn/urq6v7////+/f39/v///f7////+/////v////7////+/////v////7////+////
/v39/f7////+5+fn/nd3d/4AAAD+ERER/gUFBf4AAAD+AAAA/gUFBf4GBgb+AAAA/1xcXOQ+Pj6o
AgIC/wAAAP0BAQH9AAAA/gEBAf4BAQH+AQEB/gEBAf4AAAD+FhYW/g8PD/4AAAD+jo6O/vX19f7/
///++/v7/v////7////+qKio/gAAAP4AAAD+AAAA/mhoaP7p6en+/////v39/f79//3+/////v//
//7////+/////v////7////+/////v39/f78/Pz+/////tLS0v4BAQH+AAAA/h0dHf4AAAD+AQEB
/gEBAf0AAAD9AgIC/z4+PqhTU1OAGRkZ/wAAAP8BAQH9AgIC/wEBAf4BAQH+AQEB/gEBAf4BAQH+
AAAA/hYWFv4PDw/+AAAA/o6Ojv7z8/P+/////vz8/P6oqKj+AAAA/gAAAP4kJCT+HBwc/gAAAP5p
aWn+6enp/v////79/f3+/////v////7////+/////v////7////+/////v39/f7////+7Ozs/oOD
g/4AAAD+DAwM/gYGBv4AAAD+AgIC/wEBAf0AAAD+GRkZ/1RUVH95eXlQMjIy/wAAAP8BAQH8AwMD
/wAAAP4BAQH+AQEB/gEBAf4BAQH+AQEB/gAAAP4WFhb+ExMT/gAAAP6UlJT+7u7u/q+vr/4AAAD+
AAAA/iAgIP4AAAD+Dg4O/h8fH/4AAAD+aGho/unp6f7////+/f39/v////7////+/////v////7/
///+/f39/v////7t7e3+dXV1/gAAAP4JCQn+Dg4O/gAAAP4BAQH+AwMD/wEBAfwAAAD/NDQ0/3l5
eVCjo6McSEhI3wAAAP8BAQH8BAQE/gAAAP4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4AAAD+FhYW
/gAAAP4AAAD+VVVV/gAAAP4AAAD+HBwc/gAAAP4BAQH+AAAA/g4ODv4fHx/+AAAA/mhoaP7o6Oj+
/////v39/f79//3+/////v////78/Pz+/////u3t7f52dnb+AAAA/hwcHP4ODg7+AAAA/gEBAf4A
AAD+BAQE/gEBAfwAAAD/SUlJ36OjoxwAAAAAXFxcmA8PD/8AAAD9AwMD/QICAv8BAQH+AQEB/gEB
Af4BAQH+AQEB/gEBAf4BAQH+AAAA/hMTE/4FBQX+AAAA/gAAAP4XFxf+AAAA/gEBAf4BAQH+AQEB
/gAAAP4ODg7+Hx8f/gAAAP5oaGj+6Ojo/v////79/f3+/f39/v39/f7////+7e3t/nZ2dv4AAAD+
HR0d/hEREf4AAAD+AQEB/gEBAf4CAgL/AwMD/QAAAP0QEBD/XFxcmAAAAAAAAAAAd3d3QjU1Nf0A
AAD/BAQE/QEBAf4AAAD+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gAAAP4GBgb+HBwc/g4O
Dv4AAAD+AQEB/gEBAf4BAQH+AQEB/gEBAf4AAAD+Dw8P/h8fH/4AAAD+aWlp/ujo6P7////+/Pz8
/v////7t7e3+dnZ2/gAAAP4dHR3+Dw8P/gAAAP4BAQH+AQEB/gAAAP4BAQH+BAQE/QAAAP81NTX9
d3d3QgAAAAAAAAAA////BE9PT7MAAAD/AAAA+wEBAf4BAQH+AQEB/gICAv8CAgL/AgIC/wICAv8C
AgL/AgIC/wEBAf4CAgL/AAAA/gICAv8BAQH+AQEB/gEBAf4CAgL/AQEB/gICAv8BAQH+AAAA/w8P
D/4fHx/+AAAA/mlpaf7n5+f+/////uvr6/52dnb+AAAA/iAgIP8PDw/+AAAA/gMDA/4AAAD+AQEB
/gEBAf4BAQH+AAAA+wAAAP9PT0+z////BAAAAAAAAAABAAAAAHZ2dkk+Pj7/AAAA/wYGBvwCAgL/
AAAA/gEBAf4BAQH+AgIC/wEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4B
AQH+AQEB/gEBAf4AAAD+AwMD/gAAAP4PDw/+ICAg/gAAAP54eHj+09PT/oWFhf4AAAD+Hx8f/g8P
D/4AAAD+AwMD/gAAAP4BAQH+AAAA/gICAv8GBgb8AAAA/z4+Pv92dnZJAAAAAAAAAAEAAAADAAAA
AAAAAABmZmanAQEB/wAAAPoGBgb+AAAA/gEBAf4BAQH+AQEB/gICAv8BAQH+AgIC/wEBAf4BAQH+
AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AAAA/gMDA/4AAAD+Dw8P/gYGBv4A
AAD+AAAA/gAAAP4DAwP+Dw8P/gAAAP4FBQX/AAAA/gEBAf4BAQH+AAAA/gYGBv4AAAD6AQEB/2Zm
ZqcAAAAAAAAAAAAAAAMAAAAAAAAAAwAAAACPj48nR0dH5QAAAP8FBQX6AwMD/wAAAP4BAQH+AQEB
/gEBAf4CAgL/AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+
AQEB/gAAAP4DAwP+AAAA/g4ODv4ODg7+AAAA/goKCv4PDw/+AAAA/gUFBf8AAAD+AQEB/gEBAf4A
AAD+AwMD/wUFBfoAAAD/R0dH5Y+PjycAAAAAAAAAAwAAAAAAAAAAAAAAAgAAAAAAAAAAhISEYDs7
O/8AAAD/Dw8P+wICAv8AAAD+AgIC/wEBAf4BAQH+AgIC/wEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB
/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4AAAD+AwMD/gAAAP4FBQX+GBgY/gYGBv4AAAD+
AwMD/wAAAP4BAQH+AgIC/wAAAP4CAgL/Dw8P+wAAAP87Ozv/hISEYAAAAAAAAAAAAAAAAgAAAAAA
AAAAAAAAAAAAAAMAAAAAAAAAAGRkZIEyMjL/AAAA/wwMDPoCAgL/AAAA/gICAv8BAQH+AQEB/gEB
Af4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AAAA
/gEBAf4AAAD+AAAA/gAAAP4BAQH+AAAA/gEBAf4CAgL/AAAA/gICAv8MDAz6AAAA/zIyMv9kZGSB
AAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz8EAAAAAP///wJycnKhLi4u/wAAAP8P
Dw/7AwMD/wAAAP4AAAD+AQEB/gEBAf4CAgL/AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEB
Af4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gAAAP4AAAD+AwMD
/w8PD/sAAAD/Li4u/3JycqH///8CAAAAAD8/PwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
MzMzBQAAAAD///8IcnJyoTIyMv8AAAD/BQUF+QYGBv4CAgL/AgIC/wAAAP4BAQH+AQEB/gEBAf4B
AQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEB
Af4AAAD+AgIC/wICAv8GBgb+BQUF+QAAAP8yMjL/cnJyof///wgAAAAAMzMzBQAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAA////AmRkZIE7Ozv/AAAA/wAAAPoGBgb8
AQEB/gEBAf4CAgL/AAAA/gAAAP4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4BAQH+AQEB/gEBAf4B
AQH+AQEB/gEBAf4AAAD+AAAA/gICAv8BAQH+AQEB/gYGBvwAAAD6AAAA/zs7O/9kZGSB////AgAA
AAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzMFAAAA
AAAAAACEhIRgR0dH5QEBAf8AAAD/AAAA+wQEBPwDAwP9BAQE/gMDA/8BAQH+AgIC/wAAAP4AAAD+
AQEB/gEBAf4BAQH+AQEB/gAAAP4AAAD+AgIC/wICAv8DAwP/BAQE/gMDA/0EBAT8AAAA+wAAAP8B
AQH/R0dH5YSEhGAAAAAAAAAAADMzMwUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAPz8/BAAAAAAAAAAAj4+PJ2ZmZqc+Pj7/AAAA/wAAAP8AAAD8AQEB
/AEBAfwBAQH9AQEB/QUFBf4DAwP+AQEB/gEBAf4BAQH+AQEB/gMDA/4FBQX+AQEB/QEBAf0BAQH8
AQEB/AAAAPwAAAD/AAAA/z4+Pv9mZmanj4+PJwAAAAAAAAAAPz8/BAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAA
AAB2dnZJT09PszU1Nf0PDw//AAAA/wAAAP8AAAD+AAAA/QYGBv4HBwf/AAAA/gEBAf4BAQH+AAAA
/gcHB/8GBgb+AAAA/QAAAP4AAAD/AAAA/w8PD/81NTX9T09Ps3Z2dkkAAAAAAAAAAAAAAAAAAAAD
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAACAAAAAwAAAAAAAAAA////BHd3d0JcXFyYSEhI3zIyMv8ZGRn/AgIC/wAA
AP8AAAD+AwMD/gICAv8CAgL/AwMD/gAAAP4AAAD/AgIC/xkZGf8yMjL/SEhI31xcXJh3d3dC////
BAAAAAAAAAAAAAAAAwAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABAAAAAAAAAAAA
AAAAo6OjHHl5eVBUVFR/Pj4+qFxcXORERET/AAAA/gAAAP4AAAD+AAAA/kRERP9cXFzkPj4+qFRU
VH95eXlQo6OjHAAAAAAAAAAAAAAAAAAAAAEAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACJUE5HDQoaCgAAAA1JSERS
AAABAAAAAQAIBgAAAFxyqGYAABhSSURBVHgB7d1LjBVl3sfxorvBjEDTchNCAIcgAdHgAmYCw0I6
XNpE4guJGRcYWCjMAhYmkGDUQIaoKEEWxmRAkRUkhsTEWTAgRFiweJUYxAQSo0HBRBAFabwMffpS
7//3WP/zVjfdTffpU+fS/a3kdJ1TXZfn+Tz1f+r2VFUU0SGAAAIIIIAAAggggAACCCCAAAIIIIAA
AggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAII
IIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCA
AAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAAC
CCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggg
gAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAA
AggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAII
IIAAAggMUYFhQzTfQyrbcRwPs65febZpIpsm7tdEjIwAAmUXUKQPe+yxx+rmzp07YqCp0Tw0L80z
+Qx0lkyPAAJFFBj21FNP1dqnx2C3rfl9+/fvH/3444/Xz5w5s96W3e1H/9M4GlfT9JRGLUvLtP/3
b7eipxkyvGwCFGDZ6Ae2YAXg4cOHVX5t6TkdP358zJkzZ+omTZr0jy1btrRv3br1sVwu13j69Onf
Ll++XHP16tXo+vXr6Uny38eNGxfZdNG0adM6Fi9ePHLEiBEf79y589SuXbtqbbp/LViwoG3ZsmXN
+Qn++FJnaYktLe1dhvOzCgSoAKqgkDyJOpbfsGFD3b59+xRsHRpuw2ovXLiw/OjRo3+5efPmX69d
u7Z07969/12yZEn9pUuXoosXL/rkBfVnzJgRTZ8+PTp58uQtW/afJk6ceKKhoeGTpqamTx966KGP
7DyBB37N+vXra23ZbZw7KIi6LBNRAZSFvX8LVeBbQNeeOnUqv7U/d+5c00cffbTixo0bf//8888n
t7a2RidOnEjPWOPGY8aMqamrq6u5detW1NbWpgojPc4d33Wy0MaP6uvrNX5Hc3OzKhqtJzoPELql
S5dGw4cPjx599NErY8eOfX/58uXH5s2bd9T/r3MGVmG0UxG4CH0EChBQ4Ccn4MLU9nv8wYMHn3/6
6af/s2bNmnj27NmKZn0UpC0W7G333nuvvnfU1tbq1L//v+C+5qF5aZ6at5ahZem3fUIalBalSWlT
Gm146JR25cF/00cAgT4IKGhsd3q4j2q/G/bs2bNt48aNNxobGz2Yteuds+N2BXsIePvt/8u0rwpB
y9SylQb7KC2x0qY0Kq1Ksw0LnfKiPPlv+ggg0IPA9u3b87vaCqLdu3dvW7du3c9z5szxoM7ZyTlt
6eOamhofVra+0qC0KE2WJVUGsdKqNCvt6Yognbcess9gBIauwKZNm+7x3Nvx/D83b958Y9asWR7c
OTsu76iEoLc0epo69ZU2pdH+HyoCpV15UF48X+k8+jD6CAxpgWTLGHaRz549+7cXXnjh9OrVqz24
cqNGjeooxvG8Ifs8M+0rrUqzLS9UBMqL8qS8JQU9jL2BIb3Kk3kXSB/rHzhwYNuqVas8OG+PHz8+
nGizcX1Y1fWTPNxWHpQ35bG7vPsw+ggMGQEPfrtEt3DHjh2nV6xYoQBvt0tsrTqutu+D4qO8KE/K
m/KovCrPKmg30Hc6BIaEQHJGPJzsO3LkyHJrbeeBftsus1X9Vt8K0fPTqZ/kLewNKM/Ke1LgXC4c
Ems+mVRDnBpnsBNkK63tvQdJbjBt9S2Pnq9O/SSP4dyA8i4D90jb+DD6CAwageQGmpCfY8eO/XvR
okUhOGzL6K3mOgWLjTgof+skofKs/MlAFl7IaSMfRh+BqhdIr9iHDh06unDhQgV362De5bf89VqB
JXlvlYVMvJDTVj6MPgJVK5DetdWKPn/+fAVGy4QJE3oNEBtn0P8/MWiRSboSSJtVbcGTcARsRc43
gSX4u6/QeqkE8nasSQhUq0A426/j3GS3ny1/N3s2XgnIKHVOIN8suloLn3QPYQG/xq0z3ckJv1Z2
+7vfC7DVJE5sWmXlVwfccAivRmS9GgV8xdW1br/UN5RP+CnA+/JxI5l5OwG3rMb1gDQPQQFv567W
bt7Ix1bscNmrL0Ew1MdxK9l5i0E3HYKrE1muQoFw8kpNXpNgzlXTzTxJmvu0xc5i3MQqNBZKDLUK
cEJQCkXu8q3SijzfITu75HbXcNOLPYhTd7+1WOs3PRBjyJr0N+OykpnsZJjcQBRzK3F/JRm/pAK+
m6rbXpO7+tr9mNYSUrYtalbLtht8ivLYsZ7Sl9i1y9JvJXbjkhYsC0PgbgLp6/26993G9zvgBl3g
K28WnPHo0aNjeyhopvlL7iIMzxPwMkhb+zD6hQlwCFCY2x1T6XHdGqin33z55Zdh199W3kF5Hfv+
+++P7GnB0S+//BLZU4nDuwTuACnSgMSwRab+ZCG3LtIimA0CAxPwLZL1G+z69Q2bWzwYHuahfHT9
TJ06NQx74IEH4q+//jp+6623wu/Uo8vumKbrPPr72y1lK2ObXndVclJQEHTlF/BHd+shmEkghDPY
lrKiB0M55+nBrwY731761mIwju3dAfHrr7+eeSVg+c7JVsYqcTfXdzoEyibgWyLrN6xduzZs/ZPn
4Q3K4LetcWxvHFLsx/YyktBvb2+Pvb1DVnsCbipjWyh7AWVb41lwJwHfEulZ+MmjuwfdNX/f8qeD
X1t+dQp+72dZCXjbABnLWoXg9p0KhB8IlErAVvxwHGr98Xohhi3XH4s9aLb+vQV/iHz7U6pKIHnk
eHj5iMxVztbnXMAAVni94pmuQIErV64M/+yzzzpst3eDvafvf7755hvbK26ttZWywDlW1mQW/NF3
330X2ZY/snzqrcGRBXtkbwXqlFDbOkcdHR2RvRcgsht51Ignev/99yNz6fFNxJ1m0McfZjvMbFvt
cGCkXR24+sEHH/yvl0EfZ8FoCBRVIFxG1XvxbK7+dpxBsfXvy5bfgrFTV4o9geQNROFdhElJcim7
qKs0M+uTgD+2Sm/p1csxbaL25IGXJa0A7rnnnqK3xisk+L0myLoSSIzbZS57FZaXRZ8KjpEQKJJA
aOSza9euPclbenOlfm2Xt8LTyTnLU1E+Awn+UlQCiXFO5nb5cU9SloOywVWR1lNmk4GAn/yrtWa/
39v84+RNuUUJQs3vbp/JkyeHcdQcV+NOmjTprtPcbZ7FCP5SVAJuLXtbnp+Q4GSgFTBdCQR8l/P8
+fP23IrwXP/wim5b9ICDsC/zmDlzZliOtYyLr1+/Hr/55pvh90CuwRcz+LOuBOrq6vTylI4nVj4R
WxPhx1XkXib6TodApgK2so3QAtQqbenSpQq+FjszXtLgf/755+Nff/01xNpAW+NlEfxZVgKJdUtj
Y2O+ZaCXSaYFz8wRSAu8/PLLR+y37oxrUz/rj2/5Ffy//fZbPvj1RSffCmmIk2XwZ1kJuHlSBuli
4TsCmQqEY83jx4+PsbvSQpt/OzOd+fv8ugv+9Bn3QiqBUgR/d5WA3zswZcqUgitNN1cZqCySEuc8
QKarPjOXQFjJXn311XH2vdk+WokzrQB6C/7uAqwvewKlDP7u0vjGG2+E4NeNRQU+Ls3Nm5OysGLg
sWFCoMtQwNufv/feey8uWbJEK3Frlsf/fQn+7gKst0qgHMHvafR7CFpaWuLFixeHSmDkyJGhb5Z9
7ifmrSoDlYWK3MtG3+kQyERg7ty54QSgXYraOmPGDK2wmd3805/g9wBLHxZ0VwmUM/itubAnU0Eb
gl1tGQppP+E3B6kMVBYqbC+bTAqemSKQFrAGQHqZZWYnAAsJfo+u7iqBBx98MPZj7u7u6vNps+qn
g/+dd94Jwa/d/0KCX+5p+6Qs0sXDdwSKL2DBEY7/rX/fK6+8Ek4AeqMUW1pYKYvRH0jwewB3Vwko
bZUS/KqQBmrl9ioLlYnNj7sDhUCXmUCoAPbv3z/aGgD9bEvRgz/9ZNSAV2jNrxjB37US0Nb3tdde
C+m7fPly+Lcfi/u4WfW72/IXI/jT9ioLlUlS6lwJSCDoFV8grFy2wtXb8Wa4AmDHokWrAIoZ/B7Q
vifw+++/x99/r5az/3//vo+TVT/L4Lei1dWDYK+yUJkkxU0FUPz1njmmVy4L1Hrb/SzqJcAsgt8D
Ox2IXiH4/7Lqp5fpx/zF2vJbWfjeVqgAVBYqk3QZscYikIWAb120shWtAsgy+D3AFZDpoPThWfTT
y8kw+FUJ+N6XyoIKIIs1nnl2Eih6BeB38aWb95ZqK13lwU8F0GnV5EcpBIpWAeg6dkNDQ9iVffHF
F2N7yUaIR4I/v3vvu/m99dkDKMVazzLyAkWrAOzqQXi9ls05vGBD0e+P2c5iy5z1PEu425+uEKgA
8qsmX0ohULQKQIHvewD2TMH4hx9+CDFajXsAZQp+VQRUAKVY61lGXqCoFYDNNf8knyeffDL+8ccf
q64SKGPwUwHkV0u+lEogVADFvgyo9+ypMqi2SqDMwZ+vALgMWKrVn+WECiCLhkDVVglUQPDTEIh4
LLlAqACyagpcLZVAJQS/lXy+GTZNgUseB0NzgXaAHioA62d2M1ClVwKVEvyqALgZaOBxyFtV+mGY
3IMeWf9ne0PNx5rUbqrRmeiidd9++21klUD04YcfRs8++2z0008/hVduWeAVbRmFzsgqPuU9TP7u
u+9Gzz33XGTNe6Ovvvqq0FkOaDq3V1moTDQzL6MBzZiJEehJwB86YVufTB8IUml7ApW05bey8ceI
5XggSE9rKsMzEfDHTpXikWCVUglUWvCrAuCRYJms3sy0DwJhH7hUDwUtdyVQicGvCsA++UZAPBS0
D2stoxRNIFQApXwseLkqgQoO/pjHghdtfWZGhQqU8sUgpa4EKjn4rbzyz2LkxSCFrr1/TMdVgAL8
/DVU1pb/E3s1WNTc3Nxux6QFzKnvk5Ty6kClne3vqiRrmcteZaD/e5l0HZffvQtQAfTu09N/2/WP
pqamT+2uPn3VHx2XZtqVohKo9OBPgGVt9MNDGSTDQplkWgDMHIFEIJwHsGApy+vBszocqPTdfrNX
4OcbAPF6cOKxnAJ1Wrg9k37P7NmztWLmBvKMe5s+rNx97Re7EqiW4E+MczKXvXmpC2Xxx1f+IlAC
ATvmDAf9586da1qzZo2Ct93OTPcriG2aAY1frEqgWoJfXolxu8xlr6L2stB3OgRKKRDOodgDPf5j
C42tSWpJXhOuZflnoJVANQV/2jgxt0ER57GkQFd6gfXr14czgAcPHny+sbFRQVnSwwBbXqgICq0E
qi34ffdf1jJXiXsZ6DsdAiUVsJOAfjJw/MaNG2/YwuP6+npvoZbfSmt41p/+VgLVFvxpW1mb/Xgb
xqvAhEBXPgG/N2DPnj3b5syZE/YCkjvSMg96y3WnZfS1EqjG4E9MczKWtUrc7ctX+ix5yAuk9gIa
1q5dG/YCRo0aVZa9ACuM+G6VQDUGv/LlpjI28wateG6v73QIlE3At0S7d+/eNmvWrLAXYInptHUu
5e+eKoFqDf7ELidbGaug3Vzf6RAoq4BvibRl2rx5c9gLsNdwl20vwDC63RPwCiDj13UVveJzS9my
9S/rqs7CexLws9EnTpz45+rVqxUEt0vdLsCW2Sn4fE9g5cqV+UeO7927N4yTwYs6Oy27a1oK/Z0Y
3l61alUsW5sPZ/6FQFdZAr4XoFRZE9XT1tNDK1vVL+fHK4ENGzbEb7/9dkjLn//857KmqT8edXV1
wfCll16SaejS1j6MPgJlF9i+fXtoknr27Nm/aYtlCWofM2ZMWQ8FLA3x5MmT8wE/derU/Hf9r5I/
iV27LGVqaY3cWN/pEKg4gU2bNt2jRB04cGDbihUrFGBlPxSwNMRjx46Np0yZUtEBr3T6x3f9ZShL
Gx65rb7TIVDJAqGB0I4dO8KhgCU0V662AbbsfFBVy3e/5q/0Job2NQqm+kKHQEUL+G7qrVu3Fu7c
uTMEoO3O6n71qgvGcqTZrWQnQxW2m+o7HQIVL+BXBY4cObLc3lzjlUDZzwcYXEVXQn7ORGayU0G7
ZcUXOglEIC3gK65dv165aNEiBV7rhAkTKjoALY1lS19i0yormcnSDfWdDoFqFAhXBo4dO/bvhQsX
KrhaqATurGQSkxYZySop6GBXjYVOmhEIAulr1ocOHTo6f/58KoEuexke/LKRka86aTsfRh+BqhOw
FTn/0Aoqgc5b/16CP29WdQVOghHoKpB+bJUqgeRwoNVPetn4ZTv2Lteyk7y3yiK95U9bdXXkNwJV
K5BesXWcm5wY1Esu2odSOwHlVXm2goxlkDrm5/l+Vbt2k/A+CaQPB3Sm2y8R2sS5ct88ZGnIfC8k
yWNOy1Le/Wy/8NI2+k2HwKAUSE5uhTPcutbtjYUss7cH8yFBkrfbls9Yefbr/Pa7LjEZlOVNphDo
VsCvcau1m5q8JvcOtOsuwsG0N6C8JHf1tSuPyqu38HODboEYiMBgF0gHgG56Se4i1K74bX8Qhn3P
fNc8q2UkeQhbfeXNb+xRuabzrt90CAxJgaSde7jZRbe96nkCyUNFFPg5PQ+vmk4SKq3JM/zCsb4C
X/fz+y29lqdhtO0fkqs6me5NIH27q55+YyfIbiTPGAwVgR45XsrXj1la+7XnobQlj0UPga+0Kw/+
JB/lPZ3H3iz4HwJDUiC9ZbQTYw16COa6det+Th45HioCvYFIx9WVUBkoDUpL8lakEPhKq9KstCsP
XpDpvPkw+ggg0EVAZ8TTx8cKIj0LXy/ESN5ApIpA19Fz48aN66itrdWnX1trm7bg8bUsO6nXoWUr
DUlaYqVNaVRa04GvvChPNh4dAgj0VUBBk378tf0er1di6b14zzzzTPzII494ECsQW+wym/YM9D1U
CMU4b6B5JJVLh+atZWhZWoZ9Yr2lVy/qVJqUNqXRhodOaSfwXaMy+9TKlVkunVKlIFqyZEntqVOn
FHyhO3/+fNPx48dXXLly5e9ffPHF5NbW1siOtf3f6ocXlVrA1tjWusYuu0VtbW1qbJMe547vFvCR
jR/ZsbzG72hublagaz3J35lnW/po5MiR0cMPP3yloaHh/aampmPz5s3L38SjwD958qS3brxjGQyo
HAEqgMopi7umRBWBPd23bt++fdr9V2AqoGsvXLiw/OjRo3+5efPmX69du7bUHv39X6sw6i9duhRd
vHjxrvPtbYQZM2ZE06dPjyygb9my/zRx4sQTFvSfPPHEE5/aSb6PrMJQWtTV2K5+rS27Ldnz+GMo
fytagAqgooun58TpvoLDhw+r/PJ7BRrb9grGnDlzpm7SpEn/2LJlS/vWrVsfy+VyjadPn/7t8uXL
NVevXo2uX7/e7YztmD6y6aJp06Z1LF68eKSd2PvYWuyd2rVrV61N968FCxa0LVu2rLnLxHWWltjS
4hVBl3/zEwEEshQYpsrAPiN6WojtJdy3f//+0db2vn7mzJn1Nl63H/1P42hcTdPT/LQsLdP+zwak
JySGI1AmAQVlOHk4d+7cHiuFvqZN80hORIb59nU6xqsOAWrw6iinAaVS5w50cq8/nU0TcSzfHzHG
RQABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAA
AQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEE
EEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBA
AAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAAB
BBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQ
QAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAA
AQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEECgqgT+D0Lwnaw/FGrXAAAAAElFTkSuQmCC
#>>> copy text common followme.cfg
run_before = App::Followme::FormatPage
run_before = App::Followme::ConvertPage

#>>> copy text one-fixed styles.css
/* -----------------------
Base styles
------------------------*/

body
{
	margin: 0;
	padding: 0;
	color: #333;
	background-color: #eee;
	font: 1em/1.2 "Helvetica Neue", Helvetica, Arial, Geneva, sans-serif;
}

h1,h2,h3,h4,h5,h6
{
	margin: 0 0 .5em;
	font-weight: 500;
	line-height: 1.1;
}

h1 { font-size: 2.25em; } /* 36px */
h2 { font-size: 1.75em; } /* 28px */
h3 { font-size: 1.375em; } /* 22px */
h4 { font-size: 1.125em; } /* 18px */
h5 { font-size: 1em; } /* 16px */
h6 { font-size: .875em; } /* 14px */

p
{
	margin: 0 0 1.5em;
	line-height: 1.5;
}

blockquote
{
	padding: 1em 2em;
	margin: 0 0 2em;
	border-left: 5px solid #eee;
}

hr
{
	height: 0;
	margin-top: 1em;
	margin-bottom: 2em;
	border: 0;
	border-top: 1px solid #ddd;
}

table
{
	background-color: transparent;
	border-spacing: 0;
	border-collapse: collapse;
	border-top: 1px solid #ddd;
}

th, td
{
	padding: .5em 1em;
	vertical-align: top;
	text-align: left;
	border-bottom: 1px solid #ddd;
}

a:link { color: royalblue; }
a:visited { color: purple; }
a:focus { color: black; }
a:hover { color: green; }
a:active { color: red; }

/* -----------------------
Layout styles
------------------------*/

.container
{
	max-width: 50em;
	margin: 0 auto;
	background-color: #fff;
}

.header
{
	color: #fff;
	background: #555;
	padding: 1em 1.25em;
}

.header-heading { margin: 0; }

.nav-bar
{
	background: #000;
	padding: 0;
}

.content { padding: 1em 1.25em; }

.footer
{
	color: #fff;
	background: #000;
	padding: 1em 1.25em;
}

/* -----------------------
Nav
------------------------*/

.nav
{
	margin: 0;
	padding: 0;
	list-style: none;
}

.nav li
{
	display: inline;
	margin: 0;
}

.nav a
{
	display: block;
	padding: .7em 1.25em;
	color: #fff;
	text-decoration: none;
	border-bottom: 1px solid gray;
}

.nav a:link { color: white; }
.nav a:visited { color: white; }

.nav a:focus
{
	color: black;
	background-color: white;
}

.nav a:hover
{
	color: white;
	background-color: green;
}

.nav a:active
{
	color: white;
	background-color: red;
}

/* -----------------------
Single styles
------------------------*/

.img-responsive { max-width: 100%; }

.btn
{
	color: #fff !important;
	background-color: royalblue;
	border-color: #222;
	display: inline-block;
	padding: .5em 1em;
	margin-bottom: 0;
	font-weight: 400;
	line-height: 1.2;
	text-align: center;
	white-space: nowrap;
	vertical-align: middle;
	cursor: pointer;
	border: 1px solid transparent;
	border-radius: .2em;
	text-decoration: none;
}

.btn:hover
{
	color: #fff !important;
	background-color: green;
}

.btn:focus
{
	color: #fff !important;
	background-color: black;
}

.btn:active
{
	color: #fff !important;
	background-color: red;
}

.table
{
	width: 100%;
	max-width: 100%;
	margin-bottom: 20px;
}

.list-unstyled
{
	padding-left: 0;
	list-style: none;
}

.list-inline
{
	padding-left: 0;
	margin-left: -5px;
	list-style: none;
}

.list-inline > li
{
	display: inline-block;
	padding-right: 5px;
	padding-left: 5px;
}

/* -----------------------
Wide styles
------------------------*/

@media (min-width: 42em)
{
	.header { padding: 1.5em 3em; }
	.nav-bar { padding: 1em 3em; }
	.content { padding: 2em 3em; }
	.footer { padding: 2em 3em; }

	.nav li
	{
		display: inline;
		margin: 0 1em 0 0;
	}

	.nav a
	{
		display: inline;
		padding: 0;
		border-bottom: 0;
	}
}
#>>> copy text one-fixed index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>One-column fixed-width responsive layout</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
		<meta name="author" content="ADD AUTHOR INFORMATION">
		<meta name="robots" content="index, follow">

		<!-- icons -->
		<link rel="apple-touch-icon" href="apple-touch-icon.png">
		<link rel="shortcut icon" href="favicon.ico">

		<!-- Override CSS file - add your own CSS rules -->
		<link rel="stylesheet" href="styles.css">
	</head>
	<body>
		<div class="container">
			<div class="header">
				<h1 class="header-heading">Sitename</h1>
			</div>
			<div class="nav-bar">
				<ul class="nav">
					<li><a href="#">Nav item 1</a></li>
					<li><a href="#">Nav item 2</a></li>
					<li><a href="#">Nav item 3</a></li>
				</ul>
			</div>
			<div class="content">
				<div class="main">

					<h1>Page title</h1>
					<hr>

					<!-- Heading levels -->
					<h1>Heading level 1</h1>
					<h2>Heading level 2</h2>
					<h3>Heading level 3</h3>
					<h4>Heading level 4</h4>
					<h5>Heading level 5</h5>
					<h6>Heading level 6</h6>
					<hr>

					<!-- Paragraphs -->
					<h3>Paragraphs</h3>
					<p>Ut wisi enim ad minim veniam, <a href="#">quis nostrud exerci tation ullamcorper</a> suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
					<p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
					<hr>

					<!-- Responsive images -->
					<h3>Responsive images</h3>
					<p>For images to be responsive (so that they will rescale to suit the width of the parent, use the <code>.img-responsive</code> class.</p>
					<p><img class="img-responsive" src="http://placehold.it/800x350" alt=""></p>

					<!-- Lists -->
					<h3>Unordered list</h3>
					<p>Unordered lists are used to markup lists where list items do not require numbering.</p>
					<ul>
						<li>Ut wisi enim ad minim veniam</li>
						<li>Quis nostrud exerci tation</li>
						<li>Lamcorper suscipit lobortis nis</li>
						<li>Ut aliquip ex ea commodo consequat</li>
						<li>Duis autem vel eum iriure dolor</li>
					</ul>
					<hr>

					<h3>Ordered list</h3>
					<p>Ordered lists are used to markup lists where list items require numbering.</p>
					<ol>
						<li>Hendrerit in vulputate velit esse</li>
						<li>Olestie consequat</li>
						<li>Vel illum dolore eu feugiat</li>
						<li>Nulla facilisis at vero eros</li>
						<li>Accumsan et iusto odio</li>
					</ol>
					<hr>

					<h3>Unstyled list</h3>
					<p>You can make the list unstyled using the <code>list-unstyled</code> class.</p>
					<ul class="list-unstyled">
						<li>Ut wisi enim ad minim veniam</li>
						<li>Quis nostrud exerci tation</li>
						<li>Lamcorper suscipit lobortis nis</li>
						<li>Ut aliquip ex ea commodo consequat</li>
						<li>Duis autem vel eum iriure dolor</li>
					</ul>
					<hr>

					<h3>Inline list</h3>
					<p>You can make the list display inline using the <code>list-inline</code> class.</p>
					<ul class="list-inline">
						<li>One</li>
						<li>Two</li>
						<li>Three</li>
						<li>Four</li>
					</ul>
					<hr>

					<!-- Blockquotes -->
					<h3>Blockquotes</h3>
					<p>The blockquote element is used to markup long quotations. Ideally, content inside should be wrapped in paragraph elements.</p>
					<blockquote>
						<p>The real names of our people were destroyed during slavery. The last name of my forefathers was taken from them when they were brought to America and made slaves, and then the name of the slave master was given, which we refuse, we reject that name today and refuse it. I never acknowledge it whatsoever.</p>
						<footer><a href="http://en.wikipedia.org/wiki/Malcolm_X">Malcolm X</a></footer>
					</blockquote>
					<hr>

					<h3>Buttons</h3>
					<p>You can apply the <code>btn</code> class to any element that requires a button style.</p>
					<p><a href="#" class="btn">Submit</a></p>
					<hr>

					<!-- Tables -->
					<h3>Tables</h3>
					<p>Tables should be given the class of <code>table</code>.</p>
					<table class="table table-striped">
						<thead>
							<tr>
								<th>#</th>
								<th>First Name</th>
								<th>Last Name</th>
								<th>Username</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th scope="row">1</th>
								<td>Mark</td>
								<td>Otto</td>
								<td>@mdo</td>
							</tr>
							<tr>
								<th scope="row">2</th>
								<td>Jacob</td>
								<td>Thornton</td>
								<td>@fat</td>
							</tr>
							<tr>
								<th scope="row">3</th>
								<td>Larry</td>
								<td>the Bird</td>
								<td>@twitter</td>
							</tr>
						</tbody>
					</table>

				</div>
			</div>
			<div class="footer">
				&copy; Copyright 2015
			</div>
		</div>
	</body>
</html>
#>>> copy text two-full styles.css
/* -----------------------
Base styles
------------------------*/

body
{
	margin: 0;
	padding: 0;
	color: #333;
	background-color: #eee;
	font: 1em/1.2 "Helvetica Neue", Helvetica, Arial, Geneva, sans-serif;
}

h1,h2,h3,h4,h5,h6
{
	margin: 0 0 .5em;
	font-weight: 500;
	line-height: 1.1;
}

h1 { font-size: 2.25em; } /* 36px */
h2 { font-size: 1.75em; } /* 28px */
h3 { font-size: 1.375em; } /* 22px */
h4 { font-size: 1.125em; } /* 18px */
h5 { font-size: 1em; } /* 16px */
h6 { font-size: .875em; } /* 14px */

p
{
	margin: 0 0 1.5em;
	line-height: 1.5;
}

blockquote
{
	padding: 1em 2em;
	margin: 0 0 2em;
	border-left: 5px solid #eee;
}

hr
{
	height: 0;
	margin-top: 1em;
	margin-bottom: 2em;
	border: 0;
	border-top: 1px solid #ddd;
}

table
{
	background-color: transparent;
	border-spacing: 0;
	border-collapse: collapse;
	border-top: 1px solid #ddd;
}

th, td
{
	padding: .5em 1em;
	vertical-align: top;
	text-align: left;
	border-bottom: 1px solid #ddd;
}

a:link { color: royalblue; }
a:visited { color: purple; }
a:focus { color: black; }
a:hover { color: green; }
a:active { color: red; }

/* -----------------------
Layout styles
------------------------*/

.container
{
	max-width: 70em;
	margin: 0 auto;
}

.header
{
	color: #fff;
	background: #555;
	padding: 1em 1.25em;
}

.header-heading { margin: 0; }

.nav-bar
{
	background: #000;
	padding: 0;
}

.content
{
	overflow: hidden;
	padding: 1em 1.25em;
	background-color: #fff;
}

.main, .aside
{
	margin-bottom: 1em;
}

.footer
{
	color: #fff;
	background: #000;
	padding: 1em 1.25em;
}

/* -----------------------
Nav
------------------------*/

.nav
{
	margin: 0;
	padding: 0;
	list-style: none;
}

.nav li
{
	display: inline;
	margin: 0;
}

.nav a
{
	display: block;
	padding: .7em 1.25em;
	color: #fff;
	text-decoration: none;
	border-bottom: 1px solid gray;
}

.nav a:link { color: white; }
.nav a:visited { color: white; }

.nav a:focus
{
	color: black;
	background-color: white;
}

.nav a:hover
{
	color: white;
	background-color: green;
}

.nav a:active
{
	color: white;
	background-color: red;
}

/* -----------------------
Single styles
------------------------*/

.img-responsive { max-width: 100%; }

.btn
{
	color: #fff !important;
	background-color: royalblue;
	border-color: #222;
	display: inline-block;
	padding: .5em 1em;
	margin-bottom: 0;
	font-weight: 400;
	line-height: 1.2;
	text-align: center;
	white-space: nowrap;
	vertical-align: middle;
	cursor: pointer;
	border: 1px solid transparent;
	border-radius: .2em;
	text-decoration: none;
}

.btn:hover
{
	color: #fff !important;
	background-color: green;
}

.btn:focus
{
	color: #fff !important;
	background-color: black;
}

.btn:active
{
	color: #fff !important;
	background-color: red;
}

.table
{
	width: 100%;
	max-width: 100%;
	margin-bottom: 20px;
}

.list-unstyled
{
	padding-left: 0;
	list-style: none;
}

.list-inline
{
	padding-left: 0;
	margin-left: -5px;
	list-style: none;
}

.list-inline > li
{
	display: inline-block;
	padding-right: 5px;
	padding-left: 5px;
}

/* -----------------------
Wide styles
------------------------*/

@media (min-width: 55em)
{
	.header { padding: 1.5em 3em; }
	.nav-bar { padding: 1em 3em; }
	.content { padding: 2em 3em; }

	.main
	{
		float: left;
		width: 65%;
		margin-right: 5%;
		margin-bottom: 1em;
	}

	.aside
	{
		float: left;
		width: 30%;
		margin-bottom: 1em;
	}

	.footer { padding: 2em 3em; }

	.nav li
	{
		display: inline;
		margin: 0 1em 0 0;
	}

	.nav a
	{
		display: inline;
		padding: 0;
		border-bottom: 0;
	}
}
#>>> copy text two-full index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Two-column full width responsive layout</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
		<meta name="author" content="ADD AUTHOR INFORMATION">
		<meta name="robots" content="index, follow">

		<!-- icons -->
		<link rel="apple-touch-icon" href="apple-touch-icon.png">
		<link rel="shortcut icon" href="favicon.ico">

		<!-- Override CSS file - add your own CSS rules -->
		<link rel="stylesheet" href="styles.css">
	</head>
	<body>
		<div class="header">
			<div class="container">
				<h1 class="header-heading">Sitename</h1>
			</div>
		</div>
		<div class="nav-bar">
			<div class="container">
				<ul class="nav">
					<li><a href="#">Nav item 1</a></li>
					<li><a href="#">Nav item 2</a></li>
					<li><a href="#">Nav item 3</a></li>
				</ul>
			</div>
		</div>
		<div class="content">
			<div class="container">
				<div class="main">
					<h1>Page title</h1>
					<hr>

					<!-- Heading levels -->
					<h1>Heading level 1</h1>
					<h2>Heading level 2</h2>
					<h3>Heading level 3</h3>
					<h4>Heading level 4</h4>
					<h5>Heading level 5</h5>
					<h6>Heading level 6</h6>
					<hr>

					<!-- Paragraphs -->
					<h3>Paragraphs</h3>
					<p>Ut wisi enim ad minim veniam, <a href="#">quis nostrud exerci tation ullamcorper</a> suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
					<p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
					<hr>

					<!-- Responsive images -->
					<h3>Responsive images</h3>
					<p>For images to be responsive (so that they will rescale to suit the width of the parent, use the <code>.img-responsive</code> class.</p>
					<p><img class="img-responsive" src="http://placehold.it/800x350" alt=""></p>

					<!-- Lists -->
					<h3>Unordered list</h3>
					<p>Unordered lists are used to markup lists where list items do not require numbering.</p>
					<ul>
						<li>Ut wisi enim ad minim veniam</li>
						<li>Quis nostrud exerci tation</li>
						<li>Lamcorper suscipit lobortis nis</li>
						<li>Ut aliquip ex ea commodo consequat</li>
						<li>Duis autem vel eum iriure dolor</li>
					</ul>
					<hr>

					<h3>Ordered list</h3>
					<p>Ordered lists are used to markup lists where list items require numbering.</p>
					<ol>
						<li>Hendrerit in vulputate velit esse</li>
						<li>Olestie consequat</li>
						<li>Vel illum dolore eu feugiat</li>
						<li>Nulla facilisis at vero eros</li>
						<li>Accumsan et iusto odio</li>
					</ol>
					<hr>

					<h3>Unstyled list</h3>
					<p>You can make the list unstyled using the <code>list-unstyled</code> class.</p>
					<ul class="list-unstyled">
						<li>Ut wisi enim ad minim veniam</li>
						<li>Quis nostrud exerci tation</li>
						<li>Lamcorper suscipit lobortis nis</li>
						<li>Ut aliquip ex ea commodo consequat</li>
						<li>Duis autem vel eum iriure dolor</li>
					</ul>
					<hr>

					<h3>Inline list</h3>
					<p>You can make the list display inline using the <code>list-inline</code> class.</p>
					<ul class="list-inline">
						<li>One</li>
						<li>Two</li>
						<li>Three</li>
						<li>Four</li>
					</ul>
					<hr>

					<!-- Blockquotes -->
					<h3>Blockquotes</h3>
					<p>The blockquote element is used to markup long quotations. Ideally, content inside should be wrapped in paragraph elements.</p>
					<blockquote>
						<p>The real names of our people were destroyed during slavery. The last name of my forefathers was taken from them when they were brought to America and made slaves, and then the name of the slave master was given, which we refuse, we reject that name today and refuse it. I never acknowledge it whatsoever.</p>
						<footer><a href="http://en.wikipedia.org/wiki/Malcolm_X">Malcolm X</a></footer>
					</blockquote>
					<hr>

					<h3>Buttons</h3>
					<p>You can apply the <code>btn</code> class to any element that requires a button style.</p>
					<p><a href="#" class="btn">Submit</a></p>
					<hr>

					<!-- Tables -->
					<h3>Tables</h3>
					<p>Tables should be given the class of <code>table</code>.</p>
					<table class="table table-striped">
						<thead>
							<tr>
								<th>#</th>
								<th>First Name</th>
								<th>Last Name</th>
								<th>Username</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th scope="row">1</th>
								<td>Mark</td>
								<td>Otto</td>
								<td>@mdo</td>
							</tr>
							<tr>
								<th scope="row">2</th>
								<td>Jacob</td>
								<td>Thornton</td>
								<td>@fat</td>
							</tr>
							<tr>
								<th scope="row">3</th>
								<td>Larry</td>
								<td>the Bird</td>
								<td>@twitter</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="aside">
					<h3>Sidebar</h3>
					<p>Ut wisi enim ad minim veniam, <a href="#">quis nostrud exerci tation ullamcorper</a> suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
				</div>
			</div>
		</div>
		<div class="footer">
			<div class="container">
				&copy; Copyright 2015
			</div>
		</div>
	</body>
</html>
#>>> copy text three-full styles.css
/* -----------------------
Base styles
------------------------*/

body
{
	margin: 0;
	padding: 0;
	color: #333;
	background-color: #eee;
	font: 1em/1.2 "Helvetica Neue", Helvetica, Arial, Geneva, sans-serif;
}

h1,h2,h3,h4,h5,h6
{
	margin: 0 0 .5em;
	font-weight: 500;
	line-height: 1.1;
}

h1 { font-size: 2.25em; } /* 36px */
h2 { font-size: 1.75em; } /* 28px */
h3 { font-size: 1.375em; } /* 22px */
h4 { font-size: 1.125em; } /* 18px */
h5 { font-size: 1em; } /* 16px */
h6 { font-size: .875em; } /* 14px */

p
{
	margin: 0 0 1.5em;
	line-height: 1.5;
}

blockquote
{
	padding: 1em 2em;
	margin: 0 0 2em;
	border-left: 5px solid #eee;
}

hr
{
	height: 0;
	margin-top: 1em;
	margin-bottom: 2em;
	border: 0;
	border-top: 1px solid #ddd;
}

table
{
	background-color: transparent;
	border-spacing: 0;
	border-collapse: collapse;
	border-top: 1px solid #ddd;
}

th, td
{
	padding: .5em 1em;
	vertical-align: top;
	text-align: left;
	border-bottom: 1px solid #ddd;
}

a:link { color: royalblue; }
a:visited { color: purple; }
a:focus { color: black; }
a:hover { color: green; }
a:active { color: red; }

/* -----------------------
Layout styles
------------------------*/

.container
{
	max-width: 80em;
	margin: 0 auto;
}

.header
{
	color: #fff;
	background: #555;
	padding: 1em 1.25em;
}

.header-heading { margin: 0; }

.nav-bar
{
	background: #000;
	padding: 0;
}

.content
{
	overflow: hidden;
	padding: 1em 1.25em;
	background-color: #fff;
}

.col1,.col2,.col3
{
	margin-bottom: 1em;
}

.footer
{
	color: #fff;
	background: #000;
	padding: 1em 1.25em;
}

/* -----------------------
Nav
------------------------*/

.nav
{
	margin: 0;
	padding: 0;
	list-style: none;
}

.nav li
{
	display: inline;
	margin: 0;
}

.nav a
{
	display: block;
	padding: .7em 1.25em;
	color: #fff;
	text-decoration: none;
	border-bottom: 1px solid gray;
}

.nav a:link { color: white; }
.nav a:visited { color: white; }

.nav a:focus
{
	color: black;
	background-color: white;
}

.nav a:hover
{
	color: white;
	background-color: green;
}

.nav a:active
{
	color: white;
	background-color: red;
}

/* -----------------------
Single styles
------------------------*/

.img-responsive { max-width: 100%; }

.btn
{
	color: #fff !important;
	background-color: royalblue;
	border-color: #222;
	display: inline-block;
	padding: .5em 1em;
	margin-bottom: 0;
	font-weight: 400;
	line-height: 1.2;
	text-align: center;
	white-space: nowrap;
	vertical-align: middle;
	cursor: pointer;
	border: 1px solid transparent;
	border-radius: .2em;
	text-decoration: none;
}

.btn:hover
{
	color: #fff !important;
	background-color: green;
}

.btn:focus
{
	color: #fff !important;
	background-color: black;
}

.btn:active
{
	color: #fff !important;
	background-color: red;
}

.table
{
	width: 100%;
	max-width: 100%;
	margin-bottom: 20px;
}

.list-unstyled
{
	padding-left: 0;
	list-style: none;
}

.list-inline
{
	padding-left: 0;
	margin-left: -5px;
	list-style: none;
}

.list-inline > li
{
	display: inline-block;
	padding-right: 5px;
	padding-left: 5px;
}

/* -----------------------
Wide styles
------------------------*/

@media (min-width: 60em)
{
	.header { padding: 1.5em 2em; }
	.nav-bar { padding: 1em 2em; }
	.content { padding: 2em 2em; }

	.col1
	{
		float: left;
		width: 48%;
		margin-right: 4%;
	}

	.col2
	{
		float: left;
		width: 22%;
		margin-right: 4%;
	}

	.col3
	{
		float: left;
		width: 22%;
	}

	.footer { padding: 2em 3em; }

	.nav li
	{
		display: inline;
		margin: 0 1em 0 0;
	}

	.nav a
	{
		display: inline;
		padding: 0;
		border-bottom: 0;
	}
}
#>>> copy text three-full index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Three-column full-width responsive layout</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
		<meta name="author" content="ADD AUTHOR INFORMATION">
		<meta name="robots" content="index, follow">

		<!-- icons -->
		<link rel="apple-touch-icon" href="apple-touch-icon.png">
		<link rel="shortcut icon" href="favicon.ico">

		<!-- Override CSS file - add your own CSS rules -->
		<link rel="stylesheet" href="styles.css">
	</head>
	<body>
		<div class="header">
			<div class="container">
				<h1 class="header-heading">Sitename</h1>
			</div>
		</div>
		<div class="nav-bar">
			<div class="container">
				<ul class="nav">
					<li><a href="#">Nav item 1</a></li>
					<li><a href="#">Nav item 2</a></li>
					<li><a href="#">Nav item 3</a></li>
				</ul>
			</div>
		</div>
		<div class="content">
			<div class="container">
				<div class="col1">
					<h1>Page title</h1>
					<hr>

					<!-- Heading levels -->
					<h1>Heading level 1</h1>
					<h2>Heading level 2</h2>
					<h3>Heading level 3</h3>
					<h4>Heading level 4</h4>
					<h5>Heading level 5</h5>
					<h6>Heading level 6</h6>
					<hr>

					<!-- Paragraphs -->
					<h3>Paragraphs</h3>
					<p>Ut wisi enim ad minim veniam, <a href="#">quis nostrud exerci tation ullamcorper</a> suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
					<p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
					<hr>

					<!-- Responsive images -->
					<h3>Responsive images</h3>
					<p>For images to be responsive (so that they will rescale to suit the width of the parent, use the <code>.img-responsive</code> class.</p>
					<p><img class="img-responsive" src="http://placehold.it/800x350" alt=""></p>

					<!-- Lists -->
					<h3>Unordered list</h3>
					<p>Unordered lists are used to markup lists where list items do not require numbering.</p>
					<ul>
						<li>Ut wisi enim ad minim veniam</li>
						<li>Quis nostrud exerci tation</li>
						<li>Lamcorper suscipit lobortis nis</li>
						<li>Ut aliquip ex ea commodo consequat</li>
						<li>Duis autem vel eum iriure dolor</li>
					</ul>
					<hr>

					<h3>Ordered list</h3>
					<p>Ordered lists are used to markup lists where list items require numbering.</p>
					<ol>
						<li>Hendrerit in vulputate velit esse</li>
						<li>Olestie consequat</li>
						<li>Vel illum dolore eu feugiat</li>
						<li>Nulla facilisis at vero eros</li>
						<li>Accumsan et iusto odio</li>
					</ol>
					<hr>

					<h3>Unstyled list</h3>
					<p>You can make the list unstyled using the <code>list-unstyled</code> class.</p>
					<ul class="list-unstyled">
						<li>Ut wisi enim ad minim veniam</li>
						<li>Quis nostrud exerci tation</li>
						<li>Lamcorper suscipit lobortis nis</li>
						<li>Ut aliquip ex ea commodo consequat</li>
						<li>Duis autem vel eum iriure dolor</li>
					</ul>
					<hr>

					<h3>Inline list</h3>
					<p>You can make the list display inline using the <code>list-inline</code> class.</p>
					<ul class="list-inline">
						<li>One</li>
						<li>Two</li>
						<li>Three</li>
						<li>Four</li>
					</ul>
					<hr>

					<!-- Blockquotes -->
					<h3>Blockquotes</h3>
					<p>The blockquote element is used to markup long quotations. Ideally, content inside should be wrapped in paragraph elements.</p>
					<blockquote>
						<p>The real names of our people were destroyed during slavery. The last name of my forefathers was taken from them when they were brought to America and made slaves, and then the name of the slave master was given, which we refuse, we reject that name today and refuse it. I never acknowledge it whatsoever.</p>
						<footer><a href="http://en.wikipedia.org/wiki/Malcolm_X">Malcolm X</a></footer>
					</blockquote>
					<hr>

					<h3>Buttons</h3>
					<p>You can apply the <code>btn</code> class to any element that requires a button style.</p>
					<p><a href="#" class="btn">Submit</a></p>
					<hr>

					<!-- Tables -->
					<h3>Tables</h3>
					<p>Tables should be given the class of <code>table</code>.</p>
					<table class="table table-striped">
						<thead>
							<tr>
								<th>#</th>
								<th>First Name</th>
								<th>Last Name</th>
								<th>Username</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th scope="row">1</th>
								<td>Mark</td>
								<td>Otto</td>
								<td>@mdo</td>
							</tr>
							<tr>
								<th scope="row">2</th>
								<td>Jacob</td>
								<td>Thornton</td>
								<td>@fat</td>
							</tr>
							<tr>
								<th scope="row">3</th>
								<td>Larry</td>
								<td>the Bird</td>
								<td>@twitter</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="col2">
					<h3>Col2</h3>
					<p>Ut wisi enim ad minim veniam, <a href="#">quis nostrud exerci tation ullamcorper</a> suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
				</div>
				<div class="col3">
					<h3>Col3</h3>
					<p>Ut wisi enim ad minim veniam, <a href="#">quis nostrud exerci tation ullamcorper</a> suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
				</div>
			</div>
		</div>
		<div class="footer">
			<div class="container">
				&copy; Copyright 2015
			</div>
		</div>
	</body>
</html>
#>>> copy text one-full styles.css
/* -----------------------
Base styles
------------------------*/

body
{
	margin: 0;
	padding: 0;
	color: #333;
	background-color: #eee;
	font: 1em/1.2 "Helvetica Neue", Helvetica, Arial, Geneva, sans-serif;
}

h1,h2,h3,h4,h5,h6
{
	margin: 0 0 .5em;
	font-weight: 500;
	line-height: 1.1;
}

h1 { font-size: 2.25em; } /* 36px */
h2 { font-size: 1.75em; } /* 28px */
h3 { font-size: 1.375em; } /* 22px */
h4 { font-size: 1.125em; } /* 18px */
h5 { font-size: 1em; } /* 16px */
h6 { font-size: .875em; } /* 14px */

p
{
	margin: 0 0 1.5em;
	line-height: 1.5;
}

blockquote
{
	padding: 1em 2em;
	margin: 0 0 2em;
	border-left: 5px solid #eee;
}

hr
{
	height: 0;
	margin-top: 1em;
	margin-bottom: 2em;
	border: 0;
	border-top: 1px solid #ddd;
}

table
{
	background-color: transparent;
	border-spacing: 0;
	border-collapse: collapse;
	border-top: 1px solid #ddd;
}

th, td
{
	padding: .5em 1em;
	vertical-align: top;
	text-align: left;
	border-bottom: 1px solid #ddd;
}

a:link { color: royalblue; }
a:visited { color: purple; }
a:focus { color: black; }
a:hover { color: green; }
a:active { color: red; }

/* -----------------------
Layout styles
------------------------*/

.container
{
	max-width: 50em;
	margin: 0 auto;
}

.header
{
	color: #fff;
	background: #555;
	padding: 1em 1.25em;
}

.header-heading { margin: 0; }

.nav-bar
{
	background: #000;
	padding: 0;
}

.content
{
	padding: 1em 1.25em;
	background-color: #fff;
}

.footer
{
	color: #fff;
	background: #000;
	padding: 1em 1.25em;
}

/* -----------------------
Nav
------------------------*/

.nav
{
	margin: 0;
	padding: 0;
	list-style: none;
}

.nav li
{
	display: inline;
	margin: 0;
}

.nav a
{
	display: block;
	padding: .7em 1.25em;
	color: #fff;
	text-decoration: none;
	border-bottom: 1px solid gray;
}

.nav a:link { color: white; }
.nav a:visited { color: white; }

.nav a:focus
{
	color: black;
	background-color: white;
}

.nav a:hover
{
	color: white;
	background-color: green;
}

.nav a:active
{
	color: white;
	background-color: red;
}

/* -----------------------
Single styles
------------------------*/

.img-responsive { max-width: 100%; }

.btn
{
	color: #fff !important;
	background-color: royalblue;
	border-color: #222;
	display: inline-block;
	padding: .5em 1em;
	margin-bottom: 0;
	font-weight: 400;
	line-height: 1.2;
	text-align: center;
	white-space: nowrap;
	vertical-align: middle;
	cursor: pointer;
	border: 1px solid transparent;
	border-radius: .2em;
	text-decoration: none;
}

.btn:hover
{
	color: #fff !important;
	background-color: green;
}

.btn:focus
{
	color: #fff !important;
	background-color: black;
}

.btn:active
{
	color: #fff !important;
	background-color: red;
}

.table
{
	width: 100%;
	max-width: 100%;
	margin-bottom: 20px;
}

.list-unstyled
{
	padding-left: 0;
	list-style: none;
}

.list-inline
{
	padding-left: 0;
	margin-left: -5px;
	list-style: none;
}

.list-inline > li
{
	display: inline-block;
	padding-right: 5px;
	padding-left: 5px;
}

/* -----------------------
Wide styles
------------------------*/

@media (min-width: 42em)
{
	.header { padding: 1.5em 3em; }
	.nav-bar { padding: 1em 3em; }
	.content { padding: 2em 3em; }
	.footer { padding: 2em 3em; }

	.nav li
	{
		display: inline;
		margin: 0 1em 0 0;
	}

	.nav a
	{
		display: inline;
		padding: 0;
		border-bottom: 0;
	}
}
#>>> copy text one-full index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>One-column full-width responsive layout</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
		<meta name="author" content="ADD AUTHOR INFORMATION">
		<meta name="robots" content="index, follow">

		<!-- icons -->
		<link rel="apple-touch-icon" href="apple-touch-icon.png">
		<link rel="shortcut icon" href="favicon.ico">

		<!-- Override CSS file - add your own CSS rules -->
		<link rel="stylesheet" href="styles.css">
	</head>
	<body>
		<div class="header">
			<div class="container">
				<h1 class="header-heading">Sitename</h1>
			</div>
		</div>
		<div class="nav-bar">
			<div class="container">
				<ul class="nav">
					<li><a href="#">Nav item 1</a></li>
					<li><a href="#">Nav item 2</a></li>
					<li><a href="#">Nav item 3</a></li>
				</ul>
			</div>
		</div>
		<div class="content">
			<div class="container">
				<div class="main">
					<h1>Page title</h1>
					<hr>

					<!-- Heading levels -->
					<h1>Heading level 1</h1>
					<h2>Heading level 2</h2>
					<h3>Heading level 3</h3>
					<h4>Heading level 4</h4>
					<h5>Heading level 5</h5>
					<h6>Heading level 6</h6>
					<hr>

					<!-- Paragraphs -->
					<h3>Paragraphs</h3>
					<p>Ut wisi enim ad minim veniam, <a href="#">quis nostrud exerci tation ullamcorper</a> suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
					<p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
					<hr>

					<!-- Responsive images -->
					<h3>Responsive images</h3>
					<p>For images to be responsive (so that they will rescale to suit the width of the parent, use the <code>.img-responsive</code> class.</p>
					<p><img class="img-responsive" src="http://placehold.it/800x350" alt=""></p>

					<!-- Lists -->
					<h3>Unordered list</h3>
					<p>Unordered lists are used to markup lists where list items do not require numbering.</p>
					<ul>
						<li>Ut wisi enim ad minim veniam</li>
						<li>Quis nostrud exerci tation</li>
						<li>Lamcorper suscipit lobortis nis</li>
						<li>Ut aliquip ex ea commodo consequat</li>
						<li>Duis autem vel eum iriure dolor</li>
					</ul>
					<hr>

					<h3>Ordered list</h3>
					<p>Ordered lists are used to markup lists where list items require numbering.</p>
					<ol>
						<li>Hendrerit in vulputate velit esse</li>
						<li>Olestie consequat</li>
						<li>Vel illum dolore eu feugiat</li>
						<li>Nulla facilisis at vero eros</li>
						<li>Accumsan et iusto odio</li>
					</ol>
					<hr>

					<h3>Unstyled list</h3>
					<p>You can make the list unstyled using the <code>list-unstyled</code> class.</p>
					<ul class="list-unstyled">
						<li>Ut wisi enim ad minim veniam</li>
						<li>Quis nostrud exerci tation</li>
						<li>Lamcorper suscipit lobortis nis</li>
						<li>Ut aliquip ex ea commodo consequat</li>
						<li>Duis autem vel eum iriure dolor</li>
					</ul>
					<hr>

					<h3>Inline list</h3>
					<p>You can make the list display inline using the <code>list-inline</code> class.</p>
					<ul class="list-inline">
						<li>One</li>
						<li>Two</li>
						<li>Three</li>
						<li>Four</li>
					</ul>
					<hr>

					<!-- Blockquotes -->
					<h3>Blockquotes</h3>
					<p>The blockquote element is used to markup long quotations. Ideally, content inside should be wrapped in paragraph elements.</p>
					<blockquote>
						<p>The real names of our people were destroyed during slavery. The last name of my forefathers was taken from them when they were brought to America and made slaves, and then the name of the slave master was given, which we refuse, we reject that name today and refuse it. I never acknowledge it whatsoever.</p>
						<footer><a href="http://en.wikipedia.org/wiki/Malcolm_X">Malcolm X</a></footer>
					</blockquote>
					<hr>

					<h3>Buttons</h3>
					<p>You can apply the <code>btn</code> class to any element that requires a button style.</p>
					<p><a href="#" class="btn">Submit</a></p>
					<hr>

					<!-- Tables -->
					<h3>Tables</h3>
					<p>Tables should be given the class of <code>table</code>.</p>
					<table class="table table-striped">
						<thead>
							<tr>
								<th>#</th>
								<th>First Name</th>
								<th>Last Name</th>
								<th>Username</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th scope="row">1</th>
								<td>Mark</td>
								<td>Otto</td>
								<td>@mdo</td>
							</tr>
							<tr>
								<th scope="row">2</th>
								<td>Jacob</td>
								<td>Thornton</td>
								<td>@fat</td>
							</tr>
							<tr>
								<th scope="row">3</th>
								<td>Larry</td>
								<td>the Bird</td>
								<td>@twitter</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="footer">
			<div class="container">
				&copy; Copyright 2015
			</div>
		</div>
	</body>
</html>
#>>> copy text common templates/news_index.htm
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- section meta -->
<title>$title</title>
<!-- endsection meta -->
</head>
<body>
<div id="header">
<h1>Site Title</h1>
</div>
<div id="content">
<!-- section content -->
<h2>$title</h2>

<ul>
<!-- for @loop -->
<li><a href="$url">$title</a></li>
<!-- endfor -->
</ul>
<!-- endsection content-->
</div>
</body>
</html>

#>>> copy text common templates/news.htm
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- section meta -->
<title>$title</title>
<!-- endsection meta -->
</head>
<body>
<div id="header">
<h1>Site Title</h1>
</div>
<div id="content">
<!-- section content -->
<!-- for @loop -->
<h2>$title</h2>
$body
<p><a href="$url">Written on $month $day, $year</a></p>
<!-- endfor -->
<!-- endsection content-->
</div>
</body>
</html>

#>>> copy text common templates/page.htm
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- section meta -->
<title>$title</title>
<!-- endsection meta -->
</head>
<body>
<div id="header">
<h1>Site Title</h1>
</div>
<div id="content">
<!-- section content -->
<h2>$title</h2>
$body
<!-- endsection content-->
</div>
</body>
</html>

#>>> copy text common templates/gallery.htm
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- section meta -->
<title>$title</title>
<style>
div.float {
  float: left;
  padding: 10px;
  vertical-align: top;
  }
div.float p {
   text-align: center;
   }
</style>
<script>
var win = null;
function pop(mypage,myname,w,h){
  LeftPosition = (screen.width) ? (screen.width-w)/2 : 0;
  TopPosition = (screen.height) ? (screen.height-h)/2 : 0;
  settings = 'height='+h+',width='+w+',top='+TopPosition+
  ',left='+LeftPosition+',status=no,scrollbars=no,resizable=no'
  win = window.open(mypage,myname,settings)
}
</script>
<!-- endsection meta -->
</head>
<body>
<div id="header">
<h1>Site Title</h1>
</div>
<div id="content">
<!-- section content -->
<div class="spacer">
  &nbsp;
</div>
<!-- for @loop -->
<div class="float">
  <a target="_blank"
  onclick="pop(this.href,'_blank',
  '$photo_width','$photo_height');return false"
  href="$photo_url"><img width="$thumb_width" height="$thumb_height"
  src="$thumb_url"></a><br>
  <p>$title</p>
</div>
<!-- endfor -->
<div class="spacer">
  &nbsp;
</div>
<!-- endsection content-->
</div>
</body>
</html>
#>>> copy text common templates/index.htm
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- section meta -->
<title>$title</title>
<!-- endsection meta -->
</head>
<body>
<div id="header">
<h1>Site Title</h1>
</div>
<div id="content">
<!-- section content -->
<h2>$title</h2>

<ul>
<!-- for @loop -->
<li><a href="$url">$title</a></li>
<!-- endfor -->
</ul>
<!-- endsection content-->
</div>
</body>
</html>
